name: crowdleague
description: "Be in a league of your own..."
publish_to: 'none'

version: 0.0.5+16

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  rxdart: ^0.28.0
  geolocator: ^14.0.2
  screenshot: ^3.0.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  cloud_functions: ^6.0.0
  shared_preferences: ^2.3.5
  tutorial_coach_mark: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  fake_cloud_firestore: ^4.0.0
  firebase_storage_mocks: ^0.8.0+1
  firebase_auth_mocks: ^0.15.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_icon.png
    - assets/json/dark_mode_style.json

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf