// Flutter icons MyFlutterApp
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To add a new icon
//  - go to https://www.fluttericon.com
//  - upload ./config.json
//  - select desired icons
//  - download
//  - rename the ttf to icons.ttf and replace the one in assets/fonts/
//  - update this file
//
// The following should be in the pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  CustomIcons
//      fonts:
//       - asset: assets/fonts/icons.ttf
//
//
// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL ()
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
