// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBD19q1DpyVMUPXEr_XTvPytlh_AVVaaQ',
    appId: '1:945991608888:android:1a93eb485d7157716314cd',
    messagingSenderId: '945991608888',
    projectId: 'crowdleague-project',
    storageBucket: 'crowdleague-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAucqyBAKIpsdEs4y1M1ypgmrV1fPhyjcQ',
    appId: '1:945991608888:ios:e86c73c1fd8b65cc6314cd',
    messagingSenderId: '945991608888',
    projectId: 'crowdleague-project',
    storageBucket: 'crowdleague-project.firebasestorage.app',
    androidClientId: '945991608888-bnt33suqso037tuo91hrrgv11d7c6dno.apps.googleusercontent.com',
    iosClientId: '945991608888-2avjr1tpktuua4qv7b4gll8m13na78o5.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.cl1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCY0ns9i98D1EiGpmNrYfMzzOrpyfKL6o',
    appId: '1:945991608888:web:9552c24ac3e057566314cd',
    messagingSenderId: '945991608888',
    projectId: 'crowdleague-project',
    authDomain: 'crowdleague-project.firebaseapp.com',
    storageBucket: 'crowdleague-project.firebasestorage.app',
    measurementId: 'G-4DB55BKKJ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAucqyBAKIpsdEs4y1M1ypgmrV1fPhyjcQ',
    appId: '1:945991608888:ios:19a70067619dec436314cd',
    messagingSenderId: '945991608888',
    projectId: 'crowdleague-project',
    storageBucket: 'crowdleague-project.firebasestorage.app',
    androidClientId: '945991608888-bnt33suqso037tuo91hrrgv11d7c6dno.apps.googleusercontent.com',
    iosClientId: '945991608888-g51ifp9etckk1v70ih4n3ks2hle31p81.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.crowdleague',
  );

}