# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a signed app"
  lane :build_signed do
    # we create an unlocked keychain to avoid password prompt freeze
    create_keychain(
        name: "unlocked_keychain",
        password: "doesntmatter",
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    match(type: "appstore", 
          readonly: true, 
          keychain_name: "unlocked_keychain",
          keychain_password: "doesntmatter"
    )

    update_project_provisioning(
          profile: ENV["sigh_co.enspyr.crowdleague1_appstore_profile-path"],
          build_configuration: "Release",
          code_signing_identity: "iOS Distribution"
    )

    build_app(
        workspace: "Runner.xcworkspace", 
        scheme: "Runner", 
        export_options: {
          method: "app-store"
        }
    )
  end

  desc "Deploy latest build to TestFlight"
  lane :deploy_internal do
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end

  # combination of the above two lanes 
  desc "Build signed app and deploy to TestFlight"
  lane :build_signed_and_deploy_internal do
    # we create an unlocked keychain to avoid password prompt freeze
    create_keychain(
        name: "unlocked_keychain",
        password: "doesntmatter",
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )
    
    match(type: "appstore", 
          readonly: true, 
          keychain_name: "unlocked_keychain",
          keychain_password: "doesntmatter"
    )
    
    update_project_provisioning(
          profile: ENV["sigh_co.enspyr.crowdleague1_appstore_profile-path"],
          build_configuration: "Release",
          code_signing_identity: "iOS Distribution"
    )

    build_app(
        workspace: "Runner.xcworkspace", 
        scheme: "Runner", 
        export_options: {
          method: "app-store"
        }
    )
    
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end
