# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy a new beta build to TestFlight"
  lane :deploy_internal do
    match(type: "appstore", readonly: true)
    build_app(
        workspace: "Runner.xcworkspace", 
        scheme: "Runner", 
        export_options: {
          method: "app-store"
        }
    )
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end
end
